name: CI
on:
  push:
    branches:
      - master
      - v1
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['17.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.4
          run_install: true

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test -- --ci --coverage --maxWorkers=2

      - name: Build
        run: pnpm build

      - name: Publish Main
        run: npm publish
        if: ( ${{ github.ref }} == 'master' )
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Alpha
        run: npm publish --tag alpha
        if: ( ${{ github.ref }} != 'master' )
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

